package com.ncr.dbk.niis.model;

public enum HostAccountIdType {
	HOST_ACCOUNT_ID, ACCOUNT_NUMBER, ACH_NUMBER,

	BILL_PAY_ACCOUNT_NUMBER, CREDIT_LINE_ACCOUNT_NUMBER,

	MASTER_ACCOUNT_NUMBER, NOTE_NUMBER, MICR, PRIMARY_MEMBER,

	OVERDRAFT_ACCOUNT_NUMBER;
}
