package com.ncr.dbk.niis.model;

public enum TransferType {
	TRANSFER, TRANSFER_TO_GL, TRANSFER_TO_EXTERNAL, LOC_PAYDOWN, TRANSFER_TO_FI_OWNED, TRANSFER_FROM_FI_OWNED,
	CD_REDEMPTION, INTRA_INSTITUTION_TRANSFER, LOAN_PAYOFF, TRANSFER_FROM_GL;
}